version: '3.2'
services:
  # baseimage:
  #   build: ./baseimage
  #   image: hyperledger/fabric-baseimage:latest
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     restart_policy:
  #         condition: none
  membersrvc:
    image: ibmblockchain/fabric-membersrvc:${ARCH_TAG}
    ports:
      - "7054:7054"
    command: membersrvc
    environment:
      - MEMBERSRVC_CA_LOGGING_SERVER=INFO
      - MEMBERSRVC_CA_LOGGING_CA=INFO
      - MEMBERSRVC_CA_LOGGING_ECA=INFO
      - MEMBERSRVC_CA_LOGGING_ECAP=INFO
      - MEMBERSRVC_CA_LOGGING_ECAA=INFO
      - MEMBERSRVC_CA_LOGGING_ACA=INFO
      - MEMBERSRVC_CA_LOGGING_ACAP=INFO
      - MEMBERSRVC_CA_LOGGING_TCA=INFO
      - MEMBERSRVC_CA_LOGGING_TCAP=INFO
      - MEMBERSRVC_CA_LOGGING_TCAA=INFO
      - MEMBERSRVC_CA_LOGGING_TLSCA=INFO
      - MEMBERSRVC_CA_ACA_ENABLED=true
    networks:
      - default
      - hldemo
      - hl
    deploy:
      mode: replicated
      replicas: 1
      placement:
       constraints: [node.role == worker]
      restart_policy:
          condition: on-failure


  vp0:
    image: ibmblockchain/fabric-peer:${ARCH_TAG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: vp0
    environment:
      # - CORE_PEER_DISCOVERY_PERIOD=60s
      # - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
      # - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      - CORE_SECURITY_ENABLED=true
      #
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hl
      # - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      # - CORE_PBFT_GENERAL_MODE=batch
      # - CORE_PBFT_GENERAL_N=4
      - CORE_SECURITY_ATTRIBUTES_ENABLED=true
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_NETWORKID=dev
      - CORE_LOGGING_LEVEL=debug  #critical, error, warning, notice, info, debug
     #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_noops  # uncomment this to use specific network
      # The following section enables pbft consensus
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops  # noops, pbft
      - CORE_NOOPS_BLOCK_TIMEOUT=2s
      - CORE_NOOPS_BLOCK_WAIT=2s
    expose:
      - "7051"
      - "7052"
      - "7053"
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "sleep 25; peer node start"
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    depends_on:
      - membersrvc
    networks:
      - default
      - hldemo
      - hl
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
          condition: on-failure

  vp1:
    image: ibmblockchain/fabric-peer:${ARCH_TAG}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: vp1
    environment:
      # - CORE_PEER_DISCOVERY_PERIOD=60s
      # - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
      # - CORE_PEER_ADDRESSAUTODETECT=true
      # - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      - CORE_SECURITY_ENABLED=true
      #
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=hl
      # - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
      # - CORE_PBFT_GENERAL_MODE=batch
      # - CORE_PBFT_GENERAL_N=4
      - CORE_SECURITY_ATTRIBUTES_ENABLED=true
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_PEER_ID=vp1
      - CORE_SECURITY_ENROLLID=test_vp1
      - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
      #
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_NETWORKID=dev
      - CORE_LOGGING_LEVEL=debug  #critical, error, warning, notice, info, debug
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_noops  # uncomment this to use specific network
      # The following section enables pbft consensus
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops  # noops, pbft
      - CORE_NOOPS_BLOCK_TIMEOUT=2s
      - CORE_NOOPS_BLOCK_WAIT=2s
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "sleep 25; peer node start"
    ports:
      - "8050:7050"
      - "8051:7051"
      - "8053:7053"
    depends_on:
      - membersrvc
      - vp0
    networks:
      - default
      - hldemo
      - hl
    deploy:
      mode: replicated
      replicas: 1
      placement:
       constraints: [node.role == worker]
      restart_policy:
          condition: on-failure

  # vp2:
  #   image: ibmblockchain/fabric-peer:${ARCH_TAG}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
      # hostname: vp2
  #   environment:
  #     - CORE_PEER_DISCOVERY_PERIOD=60s
  #     - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
  #     - CORE_PEER_ADDRESSAUTODETECT=true
  #     - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
  #     - CORE_LOGGING_LEVEL=DEBUG
  #     - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
  #     - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
  #     - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
  #     - CORE_SECURITY_ENABLED=true
  #     # - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
  #     # - CORE_PBFT_GENERAL_MODE=batch
  #     # - CORE_PBFT_GENERAL_N=4
  #     - CORE_SECURITY_ATTRIBUTES_ENABLED=true
  #     - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  #     - CORE_PEER_ID=vp2
  #     - CORE_SECURITY_ENROLLID=test_vp2
  #     - CORE_SECURITY_ENROLLSECRET=vQelbRvja7cJ
  #   command: sh -c "sleep 25; peer node start"
  #   ports:
  #     - "9050:7050"
  #     - "9051:7051"
  #     - "9053:7053"
  #   depends_on:
  #     - membersrvc
  #     - vp0
  #     - vp1
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #      constraints: [node.role == manager]
  #     restart_policy:
  #         condition: on-failure
  #   networks:
  #     - default
  #     - hldemo

  # vp3:
  #   image: ibmblockchain/fabric-peer:${ARCH_TAG}
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - CORE_PEER_DISCOVERY_PERIOD=60s
  #     - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
  #     - CORE_PEER_ADDRESSAUTODETECT=true
  #     - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
  #     - CORE_LOGGING_LEVEL=DEBUG
  #     - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
  #     - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
  #     - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
  #     - CORE_SECURITY_ENABLED=true
  #     # - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft
  #     # - CORE_PBFT_GENERAL_MODE=batch
  #     # - CORE_PBFT_GENERAL_N=4
  #     - CORE_SECURITY_ATTRIBUTES_ENABLED=true
  #     - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
  #     - CORE_PEER_ID=vp3
  #     - CORE_SECURITY_ENROLLID=test_vp3
  #     - CORE_SECURITY_ENROLLSECRET=9LKqKH5peurL
  #   command: sh -c "sleep 25; peer node start"
  #   ports:
  #     - "10050:7050"
  #     - "10051:7051"
  #     - "10053:7053"
  #   depends_on:
  #     - membersrvc
  #     - vp0
  #     - vp1
  #     - vp2
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #      constraints: [node.role == manager]
  #     restart_policy:
  #         condition: on-failure
  #   networks:
  #     - default
  #     - hldemo








  # visualizer:
  #   image: dockersamples/visualizer:stable
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   deploy:
  #     placement:
  #       constraints: [node.role == worker]
  #   networks:
  #     - default
  #     - hldemo
#
#
#
#
networks:
  hldemo:
    driver: overlay
    attachable: true
  hl:
    external: true
