version: '2'
services:
  baseimage:
    build: ./baseimage
    image: hyperledger/fabric-baseimage:latest

  membersrvc:
    image: ibmblockchain/fabric-membersrvc:${ARCH_TAG}
    extends:
      file: base/membersrvc.yaml
      service: membersrvc

  vp:
    image: ibmblockchain/fabric-peer:${ARCH_TAG}
    extends:
      file: base/peer-secure-base.yaml
      service: peer-secure-base
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    environment:
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENROLLID=vp
      - CORE_SECURITY_ENROLLSECRET=f3489fy98ghf
    links:
      - membersrvc

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  monitor:
    image: endimion13/dipsup-mon-app
    environment:
      - CHAINCODE_ID=1234
    links:
      - membersrvc
      - vp
      - mongodb
