version: '3.2'
services:
 
  membersrvc:
    image: ibmblockchain/fabric-membersrvc:${ARCH_TAG}
    ports:
      - "7054:7054"
    command: membersrvc
    environment:
      - MEMBERSRVC_CA_LOGGING_SERVER=INFO
      - MEMBERSRVC_CA_LOGGING_CA=INFO
      - MEMBERSRVC_CA_LOGGING_ECA=INFO
      - MEMBERSRVC_CA_LOGGING_ECAP=INFO
      - MEMBERSRVC_CA_LOGGING_ECAA=INFO
      - MEMBERSRVC_CA_LOGGING_ACA=INFO
      - MEMBERSRVC_CA_LOGGING_ACAP=INFO
      - MEMBERSRVC_CA_LOGGING_TCA=INFO
      - MEMBERSRVC_CA_LOGGING_TCAP=INFO
      - MEMBERSRVC_CA_LOGGING_TCAA=INFO
      - MEMBERSRVC_CA_LOGGING_TLSCA=INFO
      - MEMBERSRVC_CA_ACA_ENABLED=true
    networks:
      - default
      - hldemo
      - hl
    deploy:
      mode: replicated
      replicas: 1
      placement:
       constraints: [node.role == worker]
      restart_policy:
          condition: on-failure


  vp0:
    image: hyperledger/fabric-peer:latest
    restart: unless-stopped
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_NETWORKID=dev
      - CORE_LOGGING_LEVEL=info  #critical, error, warning, notice, info, debug
     #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_noops  # uncomment this to use specific network
      # The following section enables pbft consensus
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops  # noops, pbft
      - CORE_NOOPS_BLOCK_TIMEOUT=2s
      - CORE_NOOPS_BLOCK_WAIT=2s
      - CORE_SECURITY_ATTRIBUTES_ENABLED=true
      # specific for vp0
      - CORE_PEER_ID=vp0
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
    hostname: vp0
    volumes: # docker.sock is mapped as the default CORE_VM_ENDPOINT
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "sleep 5; peer node start"
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    depends_on:
      - membersrvc
    networks:
      - default
      - hldemo
      - hl
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
          condition: on-failure

  vp1:
    image: hyperledger/fabric-peer:latest
    restart: unless-stopped
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_NETWORKID=dev
      - CORE_LOGGING_LEVEL=info  #critical, error, warning, notice, info, debug
      #- CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_noops  # uncomment this to use specific network
      # The following section enables pbft consensus
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops  # noops, pbft
      - CORE_NOOPS_BLOCK_TIMEOUT=2s
      - CORE_NOOPS_BLOCK_WAIT=2s
      - CORE_SECURITY_ATTRIBUTES_ENABLED=true
      # specific
      - CORE_PEER_ID=vp1
      - CORE_SECURITY_ENABLED=true
      - CORE_PEER_DISCOVERY_ROOTNODE=vp0:7051
      - CORE_SECURITY_ENROLLID=test_vp1
      - CORE_SECURITY_ENROLLSECRET=5wgHK9qqYaPy
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
    hostname: vp1
    depends_on:
      - membersrvc
      - vp0
    networks:
      - default
      - hldemo
      - hl
    deploy:
      mode: replicated
      replicas: 1
      placement:
       constraints: [node.role == worker]
      restart_policy:
          condition: on-failure



networks:
  hldemo:
    driver: overlay
    attachable: true
  hl:
    external: true
